# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4452926843079ac3824747540ae9a87d4ed57d112daba7039862bca007cdb0eecc3dac6be397022ad312243e8943c20e6baa9e5e8bb66924c1cda00644ea29d

test:
  secret_key_base: a2c642dffa1b87ad08475e4a37aec071d2546dfb484612bc36964d1940464349aee043bebf1b5f25d3a6e82fbc307c1cb592a64c6718a1b8c250e116b3c974c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
